### ISSUE TITLE
Check the non-linear raccoon survival curve

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/raccoon_simulation#1]

**Comment by mqwilber** [comment]
Also check whether we are double counting raccoon death

**Comment by mqwilber** [comment]
A few notes on our age-dependent survival function
1. We are modeling a "bathtub" survival function for the raccoons (https://en.wikipedia.org/wiki/Bathtub_curve).  We have a decreasing infant mortality branch, an increasing senescence branch, and a random mortality branch (constant).  This is what we want.
2. Double checked the non-linear infant mortality branch. This won't change things much, but we should weight the empirical, age-dependent survival estimates by sample size and use these new values for the infant survival curve. 
3. Depending on the above, we may need to increment `age` to `log(age + 1)` to be consistent with how we fit the survival function (line 36 in `raccoon_fxns.R`: `intrinsic_death_fxn`). I have currently made that change

**Comment by SBWeinstein** [comment]
Fit's better when weighted by sample size. sample size added to table of age dependent mortality in parameter estimates doc. 
 Weights added to function below:
fit = lm(log(y) ~ log(age + 1), weight=c(82, 24, 14, 18, 70)) # Weight by sample size!
