### ISSUE TITLE
How should raccoons disperse?

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/raccoon_simulation#12]
When a raccoon disperses at age `DISPERSAL_AGE`, we need to think about how we assign a new 
human contact probability

**Comment by mqwilber** [comment]
This might be coming up as important again.  Currently, the effect of zone-based birth control on human risk mirrors the effect of zone-based birth control on population size because sterilizing a raccoon in a zone doesn't prevent more raccoons from moving into that zone because dispersal is completely random.   So human risk will initially decrease at the same rate with increasing quota for all human zones until we begin hitting a threshold of how many raccoons are actually living in that zone .  

It might be reasonable to discuss density-dependent reproduction being zone based (i.e. depends on the density of raccoons in a zone and not in the world) and dispersal to also be density-dependent with young raccoons recruiting to less densely populated zones.  This might have interesting effects on culling as strongly culling a zone would also increase reproduction and recruitment in that zone because you are freeing up space. For birth control, sterilized females would remain in the zone and thus still take up space and resources, limiting immigration into the zone.

**Comment by SBWeinstein** [comment]
agreed. I like this idea. we already have the zone based infrastructure in the model for infection, so perhaps it wouldn't be so difficult to just steal that code and integrate it into reproduction and dispersal.  

for dispersal, perhaps we assume that raccoons are more likely to disperse to a nearby zone, and less likely to disperse to a crowded zone.  so when a raccoon draws a new zone they are most likley to go to the closest area with the fewest raccoon, plus stochasticity to keep some of them going everywhere.

**Comment by mqwilber** [comment]
Talking about how to implement this

1. Making carrying capacity zone-based. Potentially allow carrying capacity to vary with overlap? Proportional to overlap threshold?
 - Zone-based carrying capacity used in both reproduction and dispersal.

2. Make dispersal probability to any zone inversely related to how close that zone is to its carrying capacity (proportional to carrying capacity?).
  - Draw from a multinomial to decide the zone raccoons go to with probabilities given by above.

**Comment by mqwilber** [comment]
We added zone-based dispersal based on empty space in zone. I.e. raccoons are more likely to disperse to zones with more empty space.
