### ISSUE TITLE
add rodents stuff

### ISSUE THREAD

**Issue by SBWeinstein** [mqwilber/raccoon_simulation#19]
1. <s>egg infectivity cut off- 4 month</s>
2. <s>incorporating trophic transmission model</s>
3. <s>mean, aggregation of rodent worms- mouse</s>
4. <s>assume adult raccoons get rodent every other month or so, only if over 4 months</s>
5. <s>25% of rodent worms establish in raccoons</s>
6. <s>how important are rodents- keep egg worms and rodent worm matrices separate, then add together for total worm matrix.  worms senecse similarily (separate but equal)</s>

**Comment by SBWeinstein** [comment]
worms in peromyscus at COPR
data saved as peromyscus_bpdata.csv in shared IBM model dropbox folder

mu (abundance)=3.49, size (aggregation)=0.22

require(bbmle)
mice<-pero$Bp
negbin<-function(mu, size){
    -sum(dnbinom(mice, mu=mu, size=size, log=TRUE))
    }
m4<-mle2(negbin, start=list(mu=3, size=.5))

**Comment by mqwilber** [comment]
Split worm matrices into rodents and non rodents.  Might have slowed things down a little bit. See commit 29414d9 for code without the worm arrays separated.
