### ISSUE TITLE
rodent worms

### ISSUE THREAD

**Issue by SBWeinstein** [mqwilber/raccoon_simulation#27]
worms in rodents is a constant (mean worms per rodent set ~3, from SBW data). This should be a function of  eggs in the environment otherwise parasite will be maintained no matter what happens to the raccoons.  Also, check initialization of 2 rodent/non_rodent worm arrays- length of loop both non_rodent?

**Comment by mqwilber** [comment]
Added scaling of mean worm load and aggregation based on egg decay in the environment
