### ISSUE TITLE
Try making birth control zone-based

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/raccoon_simulation#33]
<s>Also, make it so you can do either birth control or culling without commenting code.</s>

Did this.

**Comment by SBWeinstein** [comment]
Also an clean up parameter value list.
maybe remove intrinsic death rate since we aren't using this anymore?

**Comment by mqwilber** [comment]
I removed some parameters that it doesn't look like we are using any more in 3c35fc1.  @zanyzooks, check out the parameters to see if there are more that we should get rid off.
