### ISSUE TITLE
Get an estimate of length of treatment effectiveness

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/raccoon_simulation#37]

**Comment by SBWeinstein** [comment]
Pyrantel Pamoate is currently used in baiting trials. Pyrantel is a depolarizing neuromuscular blocking agent. Causes paralysis in the worm. It is poorly absorbed by the gut (<7%) thus paralyzes the worms without doing damage to the host.  paralyzed worms get passed out.
Mean residence time in gut is fairly short (around 12 hours- Bjorn 1997 pig experiments), so raccoons presumably all about to get reinfected within days of dosing.
